### ISSUE TITLE
Not finding threads when url has extra queries in it

### ISSUE THREAD

**Issue by mkafrin** [hsbakshi/reddit-check#13]
I noticed the patch notes for 0.5 say this was fixed, but it still seems to be happening.

If you go to [this video](https://www.youtube.com/watch?v=n41XUnZoruU), no threads show up, but if you go to [this url](https://www.youtube.com/watch?v=n41XUnZoruU&feature=youtu.be), which just has the 
"&feature=youtu.be" query added to it, the correct thread is found

**Comment by mkafrin** [comment]
Anyone checking these?

**Comment by hsbakshi** [comment]
Weird. I will take a look over the weekend.

**Comment by mkafrin** [comment]
Any luck?

**Comment by mkafrin** [comment]
Any update?

**Comment by mmortal03** [comment]
It's probably not worth reporting this, as I don't expect this extension to be further developed, but a related issue that I've noticed from time to time is where the extension drop-down menu shows up as blank on certain URLs, but simply placing a question mark after the URL works around this.

![Reddit check no question mark](https://user-images.githubusercontent.com/8298277/131238917-0c210075-f850-4a84-804e-1438ea6ebc4f.png)

![Reddit check question mark](https://user-images.githubusercontent.com/8298277/131238921-6cc5b405-6e9c-4ea9-8d1e-4b9caf05c5e2.png)
