### ISSUE TITLE
YouTube: Check shortened link as well

### ISSUE THREAD

**Issue by Mastergalen** [hsbakshi/reddit-check#5]
It would be nice if you could add a special exception for YouTube when checking if a link has been added to YouTube.

Links to videos vary between the long format, e.g.:
https://www.youtube.com/watch?v=oHg5SJYRHA0

or  the short format:
http://youtu.be/oHg5SJYRHA0

If it could check both, that'd be great.

**Comment by jamesbvaughan** [comment]
@Mastergalen I've added this in #7

**Comment by hsbakshi** [comment]
Thanks James. I merged this fix. You should see the update in the next two days.
