### ISSUE TITLE
Randomly Opens submit page on click

### ISSUE THREAD

**Issue by mkafrin** [hsbakshi/reddit-check#9]
I love this extension, but whenever I want to open multiple reddit threads about a link, it is so difficult. First of all, whenever I try to open a thread up in a new tab, it switches to that tab immediately, and closes the list. But the main issue, is if I then try to click on the icon and open the list again, it just sends me to the submit a link page.

**Comment by hsbakshi** [comment]
Thanks for the feedback. I made a fix for the randomly opening submission link page bug. This update should rollout over the next two days.

To open links in background tabs, you can use CTRL+Click so that the link opens in a background page.
